
// Objective-C API for talking to the following Go packages
//
//	sshlib
//
// File is generated by gomobile bind. Do not edit.
#ifndef __SshLib_FRAMEWORK_H__
#define __SshLib_FRAMEWORK_H__

#include "Sshlib.objc.h"
#include "Universe.objc.h"

#endif
