// Objective-C API for talking to sshlib Go package.
//   gobind -lang=objc sshlib
//
// File is generated by gobind. Do not edit.

#ifndef __Sshlib_H__
#define __Sshlib_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT void SshlibInitSSH(NSString* _Nullable sshAddress, NSString* _Nullable socks5Address, NSString* _Nullable sshUser, NSString* _Nullable sshPass);

#endif
